apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: keptnsandbox/echo-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  kubectl:
    defaultNamespace: keptn
    manifests:
      - deploy/service.yaml
